name: "pipeline"

permissions:
  contents: write

on:
  workflow_dispatch:  
  schedule:
    - cron: "0 3 * * *"

jobs:
  pipeline:
    runs-on: ubuntu-latest

    environment: secret

    env:
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run email reporter
      run: |
        pip install -r req.txt
        echo "SMTP_USER=$SMTP_USER"
        python3 -B -m Source.Main      

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@qscvdefb@gmail.com"

    - name: Commit changes
      run: |
        git add .
        git commit -m "chore: auto update data & report" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main