name: Send Email

on:
  workflow_dispatch:  
  schedule:
    - cron: "*/2 * * * *"  

jobs:
  send:
    runs-on: ubuntu-latest

    env:
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run email reporter
      run: python3 -B -m Source.Main
